#!/usr/bin/python

import sys
import subprocess


if __name__ == '__main__':
    fname = sys.argv[1]
    for k, v in [('.go', ['go', 'run']),
                 ('.py', ['python']),
                 ('.rb', ['ruby'])]:
        print ' '.join(['---', k, '---'])
        subprocess.call(['time'] + v + [fname + k, fname + '.txt'])
